name: phpcs

on:
  pull_request:
    branches: [ "7.x", "8.x" ]
    paths:
      - "**.php"
      - "phpcs.xml"
      - ".github/workflows/phpcs.yml"

permissions:
  contents: read

jobs:
  run:
    name: Run PHP_CodeSniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: phpcs, cs2pr

      - name: Run PHPCS
        run: phpcs -q --report=checkstyle | cs2pr
